name: CDK CI
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - backend/**
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/provision-linux.sh
      - .github/workflows/provision-darwin.sh
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  cargo-clippy-cdk-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Run Clippy Linux
        run: |
          set -eExuo pipefail
          export CARGO_TERM_COLOR=always # ensure output has colors
          cargo clippy -- -Dwarnings
  cargo-test-cdk-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Run Tests Linux
        run: |
          set -eExuo pipefail
          export CARGO_TERM_COLOR=always # ensure output has colors
          cargo build --release --target wasm32-unknown-unknown --features expose-testing-api -p ic-vetkeys-manager-canister -p ic-vetkeys-encrypted-maps-canister
          cargo test
  cargo-test-cdk-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Provision Darwin
        run: |
          bash .github/workflows/provision-darwin.sh
      - name: Run Tests Darwin
        run: |
          set -eExuo pipefail
          export CARGO_TERM_COLOR=always # ensure output has colors
          cargo build --release --target wasm32-unknown-unknown --features expose-testing-api -p ic-vetkeys-manager-canister -p ic-vetkeys-encrypted-maps-canister
          cargo test
