# Known failure: https://dfinity.atlassian.net/browse/EM-7
name: encrypted-maps-example
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - cdk/**
      - sdk/ic_vetkd_sdk_encrypted_maps/**
      - sdk/ic_vetkd_sdk_encrypted_maps_example/**
      - sdk/ic_vetkd_sdk_utils/**
      - package.json
      - package-lock.json
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/encrypted-maps-example.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  encrypted-maps-example-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Provision Darwin
        run: |
          bash .github/workflows/provision-darwin.sh
      - name: Encrypted Maps Example Darwin
        run: |
          pushd cdk/encrypted_maps_example
          dfx start --background
          make mock
          eval $(make export-cmd)
          popd
          pushd sdk/ic_vetkd_sdk_encrypted_maps_example
          npm install
          npm test
          npm run lint
  encrypted-maps-example-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Encrypted Maps Example Linux
        run: |
          pushd cdk/encrypted_maps_example
          dfx start --background
          make mock
          eval $(make export-cmd)
          popd
          pushd sdk/ic_vetkd_sdk_encrypted_maps_example
          npm install
          npm test
          npm run lint
