# Known failure: https://dfinity.atlassian.net/browse/EM-7
name: encrypted-maps-example
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - cdk/encrypted-maps-example/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/provision-pocket-ic-server.sh
      - .github/workflows/encrypted-maps-example.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  encrypted-maps-example-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Provision Darwin
        run: |
          bash .github/workflows/provision-darwin.sh
          brew install llvm
      - name: Encrypted Maps Example Darwin
        run: |
          dfx start --background
          pushd cdk/encrypted_maps_example
          dfx deploy
          cargo test
  encrypted-maps-example-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Encrypted Maps Example Linux
        run: |
          dfx start --background
          pushd cdk/encrypted_maps_example
          dfx deploy
          cargo test