# Known failure: https://dfinity.atlassian.net/browse/EM-7
name: examples-password-manager
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - examples/password_manager/**
      - cdk/**
      - sdk/ic_vetkd_sdk_encrypted_maps/**
      - sdk/ic_vetkd_sdk_encrypted_maps_example,utils/**
      - sdk/ic_vetkd_sdk_utils/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/examples-password-manager.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  examples-password-manager-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Provision Darwin
        run: |
          bash .github/workflows/provision-darwin.sh
          brew install llvm
      - name: Deploy Password Manager Darwin
        run: |
          pushd examples/password_manager
          ./deploy_locally.sh
  examples-password-manager-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Deploy Password Manager Linux
        run: |
          pushd examples/password_manager
          ./deploy_locally.sh