# Known failure: https://dfinity.atlassian.net/browse/EM-7
name: examples-password-manager-with-metadata
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - examples/password_manager_with_metadata/**
      - cdk/**
      - frontend/ic_vetkd_sdk_encrypted_maps/**
      - frontend/ic_vetkd_sdk_encrypted_maps_example/**
      - frontend/ic_vetkd_sdk_utils/**
      - package.json
      - package-lock.json
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/examples-password-manager-with-metadata.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  examples-password-manager-with-metadata-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Provision Darwin
        run: |
          bash .github/workflows/provision-darwin.sh
      - name: Deploy Password Manager With Metadata Darwin
        run: |
          set -eExuo pipefail
          cd examples/password_manager_with_metadata
          ./deploy_locally.sh
          cd frontend
          npm run lint
  examples-password-manager-with-metadata-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Deploy Password Manager With Metadata Linux
        run: |
          set -eExuo pipefail
          cd examples/password_manager_with_metadata
          ./deploy_locally.sh
          cd frontend
          npm run lint