# Known failure: https://dfinity.atlassian.net/browse/EM-7
name: key-manager-example
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - backend/**
      - frontend/ic_vetkd_sdk_key_manager/**
      - frontend/ic_vetkd_sdk_key_manager_example/**
      - frontend/ic_vetkd_sdk_utils/**
      - package.json
      - package-lock.json
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/key-manager-example.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  key-manager-example-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Provision Darwin
        run: |
          bash .github/workflows/provision-darwin.sh
      - name: Key Manager Example Darwin
        run: |
          pushd backend/canisters/ic_vetkeys_manager_canister
          dfx start --background -vv
          make mock
          eval $(make export-cmd)
          popd
          pushd frontend/ic_vetkd_sdk_key_manager_example
          npm install
          npm test
          npm run lint
  key-manager-example-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Key Manager Example Linux
        run: |
          pushd backend/canisters/ic_vetkeys_manager_canister
          dfx start --background -vv
          make mock
          eval $(make export-cmd)
          popd
          pushd frontend/ic_vetkd_sdk_key_manager_example
          npm install
          npm test
          npm run lint
