name: Backend Motoko Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  backend-motoko-tests-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ZenVoich/setup-mops@v1
        with:
          mops-version: 1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Run MOPS Test Linux
        run: |
          set -eExuo pipefail
          cd backend/mo/ic_vetkeys
          mops install
          mops test
  backend-motoko-tests-darwin:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: ZenVoich/setup-mops@v1
        with:
          mops-version: 1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Run MOPS Test Darwin
        run: |
          set -eExuo pipefail
          cd backend/mo/ic_vetkeys
          mops install
          mops test
