name: key_manager
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - frontend/ic_sdk_key_manager/**
      - frontend/ic_sdk_utils/**
      - package.json
      - package-lock.json
      - .github/workflows/sdk_key_manager.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  key_manager_linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          sudo apt-get install nodejs
      - name: Test/Lint KeyManager
        run: |
          set -eExuo pipefail
          cd frontend/ic_vetkd_sdk_key_manager
          npm install
          # no tests at the moment
          npm run lint
